name: Build and deploy .NET application to container app alexw-msdocscontainerappdeploy
on:
  push:
    branches:
    - main
env:
  CONTAINER_APP_CONTAINER_NAME: msdocscontainerappdeploy
  CONTAINER_APP_NAME: alexw-msdocscontainerappdeploy
  CONTAINER_APP_RESOURCE_GROUP_NAME: msdocscontainerapps
  CONTAINER_REGISTRY_LOGIN_SERVER: msdocscontainerstore.azurecr.io
  DOCKER_FILE_PATH: msdocscontainerappdeploy/Dockerfile
  PROJECT_NAME_FOR_DOCKER: msdocscontainerappdeploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.msdocscontainerstore_USERNAME_FFFF }}
        password: ${{ secrets.msdocscontainerstore_PASSWORD_FFFF }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.alexw_msdocscontainerappdeploy_SPN }}
    - name: Deploy to containerapp
      uses: azure/CLI@v1
      with:
        inlineScript: >
          echo "Installing containerapp extension"

          az extension add --name containerapp --yes

          echo "Starting Deploying"

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username  ${{ secrets.msdocscontainerstore_USERNAME_FFFF }} --password ${{ secrets.msdocscontainerstore_PASSWORD_FFFF }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
